name: Vps Running

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: StartUP
      run: curl -sSf https://sshx.io/get | sh -s run
